"""backend/app/nlp/intent.py"""

from enum import Enum


class Intent(str, Enum):
    CURRENT_STOCK = "CURRENT_STOCK"
    LOW_STOCK = "LOW_STOCK"
    LOW_STOCK_FAST_SELLING = "LOW_STOCK_FAST_SELLING"
    STOCK_HISTORY = "STOCK_HISTORY"
    TOP_SELLING = "TOP_SELLING"
    BOTTOM_SELLING = "BOTTOM_SELLING"
    SALES_TREND = "SALES_TREND"
    REVENUE_ANALYSIS = "REVENUE_ANALYSIS"
    FINANCIAL_ANALYSIS = "FINANCIAL_ANALYSIS"
    STORE_PROFITABILITY = "STORE_PROFITABILITY"
    PRODUCT_INFO = "PRODUCT_INFO"
    DEMAND_FORECAST = "DEMAND_FORECAST"
    STOCKOUT_RISK = "STOCKOUT_RISK"
    REORDER_RECOMMENDATION = "REORDER_RECOMMENDATION"
    CATEGORY_ANALYSIS = "CATEGORY_ANALYSIS"
    STORE_ANALYSIS = "STORE_ANALYSIS"
    RECORD_SALE = "RECORD_SALE"
    RECEIVE_STOCK = "RECEIVE_STOCK"
    ADJUST_STOCK = "ADJUST_STOCK"
    HELP = "HELP"
    UNKNOWN = "UNKNOWN"


# Intents that require a resolved, existing product_id to proceed.
PRODUCT_REQUIRED_INTENTS = {
    Intent.CURRENT_STOCK,
    Intent.PRODUCT_INFO,
    Intent.DEMAND_FORECAST,
    Intent.STOCKOUT_RISK,
    Intent.REORDER_RECOMMENDATION,
}
