"""initial schema

Revision ID: 44712a0a1c01
Revises: 
Create Date: 2026-09-24 09:36:36.512097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44712a0a1c01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('daily_inventory',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('inventory_level', sa.Integer(), nullable=False),
    sa.Column('units_ordered', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('date', 'store_id', 'product_id')
    )
    op.create_table('daily_sales',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('holiday_promotion', sa.Boolean(), nullable=False),
    sa.Column('weather_condition', sa.String(length=30), nullable=False),
    sa.Column('competitor_pricing', sa.Float(), nullable=False),
    sa.Column('seasonality', sa.String(length=20), nullable=False),
    sa.Column('demand_forecast_reference', sa.Float(), nullable=False),
    sa.Column('possible_stock_constrained', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('date', 'store_id', 'product_id')
    )
    op.create_index(op.f('ix_daily_sales_category'), 'daily_sales', ['category'], unique=False)
    op.create_index(op.f('ix_daily_sales_region'), 'daily_sales', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_sales_region'), table_name='daily_sales')
    op.drop_index(op.f('ix_daily_sales_category'), table_name='daily_sales')
    op.drop_table('daily_sales')
    op.drop_table('daily_inventory')
    op.drop_table('stores')
    op.drop_table('products')
    # ### end Alembic commands ###
