"""add performance indexes

Revision ID: ef7f2d944d29
Revises: 44712a0a1c01
Create Date: 2026-09-24 09:37:38.495247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7f2d944d29'
down_revision: Union[str, None] = '44712a0a1c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_inventory_level', 'daily_inventory', ['inventory_level'], unique=False)
    op.create_index('ix_daily_inventory_product_date', 'daily_inventory', ['product_id', 'date'], unique=False)
    op.create_index('ix_daily_sales_product_date', 'daily_sales', ['product_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_sales_product_date', table_name='daily_sales')
    op.drop_index('ix_daily_inventory_product_date', table_name='daily_inventory')
    op.drop_index('ix_daily_inventory_level', table_name='daily_inventory')
    # ### end Alembic commands ###
